add-recommendations
bbzen/java-filmorate pull request #19
Opened 2023-07-19 16:19 UTC by NikolaiGurianov

2023-07-20 07:27 UTC, bbzen approved these changes

2023-07-20 07:43 UTC, bbzen requested changes

2023-07-20 07:43 UTC, bbzen commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
} забыл

2023-07-20 07:43 UTC, bbzen commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return filmStorage.getFilmsLikedUsers(userId);
нет такого метода же, у тебя он вроде как getRecommendations называется

2023-07-22 21:13 UTC, bbzen approved these changes

2023-07-22 21:15 UTC, bbzen approved these changes

2023-07-22 21:15 UTC, bbzen commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerInMemoryTest.java
Убей совсем этот файл, инМемори я уже в принципе удалил, так что тест для него тоже не нужен

2023-07-23 16:08 UTC, ablaaikhan approved these changes

2023-07-24 15:29 UTC, bbzen approved these changes

2023-07-25 06:41 UTC, merged