Add feed
bbzen/java-filmorate pull request #25
Opened 2023-07-26 14:00 UTC by ablaaikhan

add-feed

2023-07-26 16:17 UTC, bbzen requested changes

2023-07-26 16:17 UTC, bbzen commented on src/main/resources/schema.sql
>  drop table film_genres if  exists cascade;
Дропы лишние в версии для ПР, странно будет для приложения дропать таблицы при каждом запуске

2023-07-26 16:23 UTC, bbzen approved these changes

2023-07-27 09:38 UTC, rrtuyu approved these changes
все хорошо, только порт поменять нужно

2023-07-27 11:23 UTC, merged